-- Crear esquema de base de datos para calculo de prestaciones

CREATE USER PRESTACIONES IDENTIFIED BY prest2025
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Dar privilegios minimos necesarios

GRANT CONNECT, RESOURCE TO PRESTACIONES;
GRANT CREATE SESSION TO PRESTACIONES;
GRANT CREATE TABLE TO PRESTACIONES;
GRANT CREATE VIEW TO PRESTACIONES;
GRANT CREATE SEQUENCE TO PRESTACIONES;
GRANT CREATE PROCEDURE TO PRESTACIONES;
GRANT CREATE TRIGGER TO PRESTACIONES;
GRANT UNLIMITED TABLESPACE TO PRESTACIONES;


-- Usuario y contraseña para la conexión

Usuario: prestaciones
Contraseña: presta2025
